export const exampleGrpMsgReq = {
    id: 'false_628985665498-1630138627@g.us_3EB0D9B4C52EDC370597',
    body: '#reqregis cap1 | cap2',
    type: 'chat',
    t: 1630251812,
    notifyName: '',
    from: '628985665498-1630138627@g.us',
    to: '6285156526447@c.us',
    author: '628985665498@c.us',
    self: 'in',
    ack: 0,
    invis: false,
    isNewMsg: true,
    star: false,
    recvFresh: true,
    isFromTemplate: false,
    broadcast: false,
    quotedMsg: null,
    mentionedJidList: [],
    isVcardOverMmsDocument: false,
    isForwarded: false,
    labels: [],
    ephemeralOutOfSync: false,
    productHeaderImageRejected: false,
    isDynamicReplyButtonsMsg: false,
    isMdHistoryMsg: false,
    chatId: '628985665498-1630138627@g.us',
    fromMe: false,
    sender: {
        id: '628985665498@c.us',
        name: 'Rizqy',
        shortName: 'Rizqy',
        pushname: 'Rizqy Prastya A.N',
        type: 'in',
        isBusiness: false,
        isEnterprise: false,
        statusMute: false,
        labels: [],
        formattedName: 'Rizqy',
        isMe: false,
        isMyContact: true,
        isPSA: false,
        isUser: true,
        isWAContact: true,
        profilePicThumbObj: { eurl: null, id: '628985665498@c.us', tag: null },
        msgs: null
    },
    timestamp: 1630251812,
    content: '#reqregis cap1 | cap2',
    isGroupMsg: true,
    isMedia: false,
    isNotification: false,
    isPSA: false,
    chat: {
        id: '628985665498-1630138627@g.us',
        pendingMsgs: false,
        lastReceivedKey: {
            fromMe: false,
            remote: '628985665498-1630138627@g.us',
            id: '3A0057FDCE3CB660FD34',
            _serialized: 'false_628985665498-1630138627@g.us_3A0057FDCE3CB660FD34'
        },
        t: 1630251170,
        unreadCount: 1,
        archive: false,
        isReadOnly: false,
        isAnnounceGrpRestrict: false,
        muteExpiration: 0,
        name: 'Ini grup tester, mute aja',
        notSpam: true,
        pin: 0,
        msgs: null,
        kind: 'group',
        canSend: true,
        isGroup: true,
        formattedTitle: 'Ini grup tester, mute aja',
        contact: {
            id: '628985665498-1630138627@g.us',
            name: 'Ini grup tester, mute aja',
            type: 'in',
            isBusiness: false,
            isEnterprise: false,
            statusMute: false,
            labels: [],
            formattedName: 'Ini grup tester, mute aja',
            isMe: false,
            isMyContact: false,
            isPSA: false,
            isUser: false,
            isWAContact: false,
            profilePicThumbObj: [Object],
            msgs: null
        },
        groupMetadata: {
            id: '628985665498-1630138627@g.us',
            creation: 1630138627,
            owner: '628985665498@c.us',
            restrict: false,
            announce: false,
            noFrequentlyForwarded: false,
            ephemeralDuration: 0,
            support: false,
            uniqueShortNameMap: {},
            participants: [Array],
            pendingParticipants: []
        },
        presence: { id: '628985665498-1630138627@g.us', chatstates: [Array] },
        isOnline: true,
        participantsCount: 5
    },
    isOnline: true,
    quotedMsgObj: null,
    mediaData: {}
}


export const exampleUsrMsgReq = {
    id: 'false_628985665498@c.us_3EB021342B3C63A4B32F',
    body: '#regis cap1 | cap2',
    type: 'chat',
    t: 1630251906,
    notifyName: '',
    from: '628985665498@c.us',
    to: '6285156526447@c.us',
    self: 'in',
    ack: 0,
    invis: false,
    isNewMsg: true,
    star: false,
    recvFresh: true,
    isFromTemplate: false,
    broadcast: false,
    quotedMsg: null,
    mentionedJidList: [],
    isVcardOverMmsDocument: false,
    isForwarded: false,
    labels: [],
    ephemeralOutOfSync: false,
    productHeaderImageRejected: false,
    isDynamicReplyButtonsMsg: false,
    isMdHistoryMsg: false,
    chatId: '628985665498@c.us',
    fromMe: false,
    sender: {
        id: '628985665498@c.us',
        name: 'Rizqy',
        shortName: 'Rizqy',
        pushname: 'Rizqy Prastya A.N',
        type: 'in',
        isBusiness: false,
        isEnterprise: false,
        statusMute: false,
        labels: [],
        formattedName: 'Rizqy',
        isMe: false,
        isMyContact: true,
        isPSA: false,
        isUser: true,
        isWAContact: true,
        profilePicThumbObj: { eurl: null, id: '628985665498@c.us', tag: null },
        msgs: null
    },
    timestamp: 1630251906,
    content: '#regis cap1 | cap2',
    isGroupMsg: false,
    isMedia: false,
    isNotification: false,
    isPSA: false,
    chat: {
        id: '628985665498@c.us',
        pendingMsgs: false,
        lastReceivedKey: {
            fromMe: true,
            remote: '628985665498@c.us',
            id: '3EB0136B474CD52D9482',
            _serialized: 'true_628985665498@c.us_3EB0136B474CD52D9482'
        },
        t: 1630246652,
        unreadCount: 0,
        archive: false,
        isReadOnly: false,
        modifyTag: 83784,
        muteExpiration: 0,
        name: 'Rizqy',
        notSpam: true,
        pin: 0,
        ephemeralDuration: 0,
        ephemeralSettingTimestamp: 0,
        msgs: null,
        kind: 'chat',
        canSend: true,
        isGroup: false,
        formattedTitle: 'Rizqy',
        contact: {
            id: '628985665498@c.us',
            name: 'Rizqy',
            shortName: 'Rizqy',
            pushname: 'Rizqy Prastya A.N',
            type: 'in',
            isBusiness: false,
            isEnterprise: false,
            statusMute: false,
            labels: [],
            formattedName: 'Rizqy',
            isMe: false,
            isMyContact: true,
            isPSA: false,
            isUser: true,
            isWAContact: true,
            profilePicThumbObj: [Object],
            msgs: null
        },
        groupMetadata: null,
        presence: { id: '628985665498@c.us', chatstates: [] },
        isOnline: false,
        participantsCount: 1
    },
    isOnline: false,
    quotedMsgObj: null,
    mediaData: {}
}
